const GET_GENERS_REQUEST = 'GET_GENERS_REQUEST';
const GET_GENERS_REQUEST_SUCCESS = 'GET_GENERS_REQUEST_SUCCESS';
const GET_GENERS_REQUEST_FAILURE = 'GET_GENERS_REQUEST_FAILURE';

export {
  GET_GENERS_REQUEST,
  GET_GENERS_REQUEST_SUCCESS,
  GET_GENERS_REQUEST_FAILURE,
};
