const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
const GET_MOVIES_REQUEST_SUCCESS = 'GET_MOVIES_REQUEST_SUCCESS';
const GET_MOVIES_REQUEST_FAILURE = 'GET_MOVIES_REQUEST_FAILURE';

export {
  GET_MOVIES_REQUEST,
  GET_MOVIES_REQUEST_SUCCESS,
  GET_MOVIES_REQUEST_FAILURE,
};
